### ISSUE TITLE
Notice: Undefined variable: requestUri

### ISSUE THREAD

**Issue by giannign1** [intuit/QuickBooks-V3-PHP-SDK#321]
Inside https://github.com/intuit/QuickBooks-V3-PHP-SDK/blob/master/src/Core/OAuth/OAuth2/OAuth2LoginHelper.php
in many functions the variable $requestUri is used but never initialized and i have now a Notice in php7.4

**Comment by bsivalingam** [comment]
@giannign1 Can you please confirm the version of SDK you are using? It is fixed in 5.3.8.

**Comment by giannign1** [comment]
Happy to hear that!
I am not using the last release, you are right on this and i still need to try it.

But i see in the code that the variable $requestUri is still used but never allocated so i think the issue is still there (Notice since php 7.4, Warning Until php7.3.x)

Are you sure it is fixed?

**Comment by bsivalingam** [comment]
Hmm..I don't see any line of code that uses `$requestUri` but not commented out already. Can you please let me know which line you are referring to?

**Comment by giannign1** [comment]
I'm dumb! Totally!
Shame on me!
Sorry for bothering, i close the issue!
